services:
  postgres:
    image: postgres:17-alpine
    container_name: veyra_db
    environment:
      POSTGRES_USER: veyra_user
      POSTGRES_PASSWORD: veyra_pass
      POSTGRES_DB: veyra_db
    ports:
      - "5433:5432"
    volumes:
      - veyra_pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: veyra_backend
    ports:
      - "8080:8080"
    environment:
      # Aktif profili 'dev' olarak bırakıyoruz ama DB adresini Docker network'e göre eziyoruz
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/veyra_db
    depends_on:
      - postgres
    restart: always

volumes:
  veyra_pgdata:
